### ISSUE TITLE
mixture of entity refs for cut-in scenarios, false unit for deceleration?

### ISSUE THREAD

**Issue by tmIdiada** [asam-oss/OSC-ALKS-scenarios#41]
Hi,

1. in Cut-In scenarios the entity ref of Cut-In story is well defined as CutInVehicle. But the entity ref inside this story of the triggering entities is ego. Would it be not also correct and more consistent to switch the entity refs of triggering entities and relativeDistanceCondition?

2. In followLeadVehicle scenario the variable is called LeadVehicle_BrakeRate_Gx_max, which seems to lead to unit G, but it is directly the input of rate, thus I think the unit is mpss?

Kind regards,

Thaddäus

**Comment by arauschert** [comment]
Hi,

thanks for your feedback!

Regarding question 1:
Here, we have three entityRefs defined in the story. The first one is the Actor for the actions. The other two are for calculation of the relative longitudinal distance. If you use the road coordinate system (new in OSC 1.1; in OSC 1.0 it was not defined) for distance calculation, then you're right that switching these two would be also correct and result in the same execution behaviour. If you use the lane coordinate system (also OSC 1.1, we are updating the moment), which is more accurate, you would want to measure the distance on the lane of the ego vehicle, so from Ego to CutInVehicle. The annotation in OpenSCENARIO 1.1 for RelativeDistanceCondition is as follows: "The current relative distance of a triggering entity/entities to a reference entity..." 
Therefore you would need to have the Ego as TriggeringEntity. So, no change is needed. But still thanks for the hint, I didn't check this in detail yet.

Regarding question 2: 
You're right, the unit for deceleration in the SpeedAction is m/s², so it's the rate (default value is 6 m/s² and not 6 g). The name "Gx max" was taken from the ALKS regulation, so the transfer from regulation to scenario is easier, but I will change the naming of the parameter to LeadVehicle_Deceleration_Rate. It's not 100% clear what are the test requirements because in chapter 4.3.2 of the regulation a minimum of 6 m/s² is mentioned as rate, while in chapter 5.4 "-1.0" G is mentioned. 
With the update to OpenSCENARIO 1.1 and the use of expressions we can then also use g as unit for the parameter with values between 0 and 1 and calculate the rate for the SpeedAction (rate = $LeadVehicle_Deceleration_g * 9.81), which is the more strict requirement.

**Comment by tmIdiada** [comment]
Hi,

thank you for the answers, regarding point 1 I was too concentrated on straight roads, but in case of curved roads you are right, that then there is a difference in the distance.

I have found a small inconsistency in case of CutOut scenario, there is it called CutOutManeuverGroup, instead of the used CutInSequence or BrakeSequence in the other 2 scenarios, but not really important.

The more important additional issue is, why there is defined an acceleration action for cut-in vehicle, have you found some information in the regulation or comes it directly from your side and that is the reason for rate 0? If one uses here rate 0, then one can also delete this whole acceleration action, right?

**Comment by arauschert** [comment]
Thanks for the additional hints!

I renamed ...Sequence to ...ManeuverGroup now. I missed this when updating from OSC 0.9.1, where ManeuverGroups were called Sequences.

Regarding the accerleration in cut-in: You're right that when using rate 0, the action could also be removed. In chapter 4.4.3 (b) of Annex 5 acceleration and deceleration are mentioned for the Cut-In scenario, therefore the action was added in the OSC scenarios. But in Annex 4 chapter 4.3, deceleration is not mentioned as parameter for cut-In. Therefore I set the rate to 0 for testing according to the attached data sheets.
