### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by yhamadi75** [asam-oss/OSC-ALKS-scenarios#68]
Hi,
There are missing references in logical scenarios, for example "./road_networks/alks_road_straight.xodr" in alks_scenario_4_1_2_swerving_lead_vehicle_variation.xosc

Why are they absent from the directory structure (unlike reference to concrete files e.g., ./concrete_scenarios/alks_scenario_4_1_2_swerving_lead_vehicle_template.xosc)?

Thanks!

**Comment by arauschert** [comment]
Hi! 
Thanks for your question.
In the logical scenarios the value "./road_networks/alks_road_straight.xodr" is not a reference but a value for a parameter in the concrete scenario. So if you replace the parameter "Road" in the referenced concrete scenario with the value "./road_networks/alks_road_straight.xodr", then the reference can be resolved because it must be relative to the path of the concrete scenario.
Hope that answers the question.
Best regards

**Comment by yhamadi75** [comment]
Thanks for clarifying !
